terraform output json

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -40,28 +40,32 @@ jobs:
     - name: Output Terraform JSON
       working-directory: ./terraform
       run: |
-        terraform output -json
+        terraform output -json | tee terraform_output.json
+        cat terraform_output.json
 
     - name: Extract Terraform Outputs
       id: extract_outputs
       working-directory: ./terraform
       run: |
-        dynamodb_table_name=$(terraform output -json | jq -r '.dynamodb_table_name.value')
-        initialize_function_url=$(terraform output -json | jq -r '.initialize_dynamodb_url.value')
-        lambda_function_url=$(terraform output -json | jq -r '.lambda_function_url.value')
-        bucket_name=$(terraform output -json | jq -r '.bucket_name.value')
-        
-        echo "DYNAMODB_TABLE_NAME=$dynamodb_table_name"
-        echo "INITIALIZE_FUNCTION_URL=$initialize_function_url"
-        echo "LAMBDA_FUNCTION_URL=$lambda_function_url"
-        echo "BUCKET_NAME=$bucket_name"
-
-        echo "DYNAMODB_TABLE_NAME=$dynamodb_table_name" >> $GITHUB_ENV
-        echo "INITIALIZE_FUNCTION_URL=$initialize_function_url" >> $GITHUB_ENV
-        echo "LAMBDA_FUNCTION_URL=$lambda_function_url" >> $GITHUB_ENV
-        echo "BUCKET_NAME=$bucket_name" >> $GITHUB_ENV
-
+          if [ -f terraform_output.json ]; then
+            dynamodb_table_name=$(jq -r '.dynamodb_table_name.value' terraform_output.json)
+            initialize_function_url=$(jq -r '.initialize_dynamodb_url.value' terraform_output.json)
+            lambda_function_url=$(jq -r '.lambda_function_url.value' terraform_output.json)
+            bucket_name=$(jq -r '.bucket_name.value' terraform_output.json)
+            
+            echo "DYNAMODB_TABLE_NAME=$dynamodb_table_name"
+            echo "INITIALIZE_FUNCTION_URL=$initialize_function_url"
+            echo "LAMBDA_FUNCTION_URL=$lambda_function_url"
+            echo "BUCKET_NAME=$bucket_name"
   
+            echo "DYNAMODB_TABLE_NAME=$dynamodb_table_name" >> $GITHUB_ENV
+            echo "INITIALIZE_FUNCTION_URL=$initialize_function_url" >> $GITHUB_ENV
+            echo "LAMBDA_FUNCTION_URL=$lambda_function_url" >> $GITHUB_ENV
+            echo "BUCKET_NAME=$bucket_name" >> $GITHUB_ENV
+          else
+            echo "terraform_output.json not found"
+            exit 1
+          fi
 
     - name: Update scripts.js with dynamic parameters
       if: ${{ env.LAMBDA_FUNCTION_URL != '' && env.INITIALIZE_FUNCTION_URL != '' && env.DYNAMODB_TABLE_NAME != '' && env.BUCKET_NAME != '' }}
